In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Importing or reading the data from csv file.

In [3]:
matches = pd.read_csv("../Data/Raw/matches.csv")

In [4]:
deliveries = pd.read_csv("../Data/Raw/deliveries.csv")

Describing data

In [5]:
matches.describe()

                 id  result_margin  target_runs  target_overs
count  1.095000e+03    1076.000000  1092.000000   1092.000000
mean   9.048283e+05      17.259294   165.684066     19.759341
std    3.677402e+05      21.787444    33.427048      1.581108
min    3.359820e+05       1.000000    43.000000      5.000000
25%    5.483315e+05       6.000000   146.000000     20.000000
50%    9.809610e+05       8.000000   166.000000     20.000000
75%    1.254062e+06      20.000000   187.000000     20.000000
max    1.426312e+06     146.000000   288.000000     20.000000

In [6]:
deliveries.describe()

,match_id,inning,over,ball,batsman_runs,extra_runs,total_runs,is_wicket
count,2.609200e+05,260920.000000,260920.000000,260920.000000,260920.000000,260920.000000,260920.000000,260920.000000
mean,9.070665e+05,1.483531,9.197677,3.624486,1.265001,0.067806,1.332807,0.049632
std,3.679913e+05,0.502643,5.683484,1.814920,1.639298,0.343265,1.626416,0.217184
min,3.359820e+05,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,5.483340e+05,1.000000,4.000000,2.000000,0.000000,0.000000,0.000000,0.000000
50%,9.809670e+05,1.000000,9.000000,4.000000,1.000000,0.000000,1.000000,0.000000
75%,1.254066e+06,2.000000,14.000000,5.000000,1.000000,0.000000,1.000000,0.000000
max,1.426312e+06,6.000000,19.000000,11.000000,6.000000,7.000000,7.000000,1.000000

Information of the data

In [7]:
matches.info()

<class 'pandas.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   str
 2   city             1044 non-null   str
 3   date             1095 non-null   str
 4   match_type       1095 non-null   str
 5   player_of_match  1090 non-null   str
 6   venue            1095 non-null   str
 7   team1            1095 non-null   str
 8   team2            1095 non-null   str
 9   toss_winner      1095 non-null   str
 10  toss_decision    1095 non-null   str
 11  winner           1090 non-null   str
 12  result           1095 non-null   str
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   str
 17  method           21 non-null     str
 18  umpire1          1095 non-null   str
 19  umpire2          1095 non-null   str
dtypes: float64(3), int64(1), str(16)
memory usage: 171.2 KB

In [8]:
deliveries.info()

<class 'pandas.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   inning            260920 non-null  int64
 2   batting_team      260920 non-null  str
 3   bowling_team      260920 non-null  str
 4   over              260920 non-null  int64
 5   ball              260920 non-null  int64
 6   batter            260920 non-null  str
 7   bowler            260920 non-null  str
 8   non_striker       260920 non-null  str
 9   batsman_runs      260920 non-null  int64
 10  extra_runs        260920 non-null  int64
 11  total_runs        260920 non-null  int64
 12  extras_type       14125 non-null   str
 13  is_wicket         260920 non-null  int64
 14  player_dismissed  12950 non-null   str
 15  dismissal_kind    12950 non-null   str
 16  fielder           9354 non-null    str
dtypes: int64(8), str(9)
memory usage: 33.8 MB

Shape Of the Data

In [9]:
matches.shape

(1095, 20)

In [10]:
deliveries.shape

(260920, 17)

Looking for the null values

In [11]:
matches.isnull().sum()

id                    0
season                0
city                 51
date                  0
match_type            0
player_of_match       5
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                5
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

In [12]:
deliveries.isnull().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type         246795
is_wicket                0
player_dismissed    247970
dismissal_kind      247970
fielder             251566
dtype: int64

#Cleaning the Data (Matches Table)

In [13]:
#Changing Date datatype
matches['date'] = pd.to_datetime(
    matches['date'],
    format='%d-%m-%Y'

)

#Replacing Null Value Of method
matches['method'] = matches['method'].fillna('Normal')


#Droping null values from Winner of Matches table
matches = matches.dropna(subset=['winner'])


#Replacing Null values in City
matches['city'] = matches['city'].fillna('Dubai')

#Replacing null values in result_margin
matches['result_margin'] = matches['result_margin'].fillna(0)

Cleaning the data for Deliveries Table

In [14]:
#Replacing Null values
deliveries['extras_type'] = deliveries['extras_type'].fillna('no_extra')
deliveries['player_dismissed'] = deliveries['player_dismissed'].fillna('not_out')
deliveries['dismissal_kind'] = deliveries['dismissal_kind'].fillna('no_dismissal')

needs_fielder = ['caught', 'stumped', 'run out', 'caught and bowled']
no_fielder = ['bowled', 'lbw', 'hit wicket', 'no_dismissal']

deliveries['fielder'] = np.where(
    deliveries['dismissal_kind'].isin(no_fielder) & deliveries['fielder'].isna(),
    'no_fielder',
    np.where(
        deliveries['dismissal_kind'].isin(needs_fielder) & deliveries['fielder'].isna(),
        'unknown',
        deliveries['fielder']
    )
)

#Fixing Team Name

In [15]:
team_name_change = {
    'Delhi Daredevils': 'Delhi Capitals',
    'Kings XI Punjab': 'Punjab Kings',
    'Royal Challengers Bangalore': 'Royal Challengers Bengaluru',
    'Rising Pune Supergiant': 'Rising Pune Supergiants'
    }
matches.replace(team_name_change, inplace=True)
deliveries.replace(team_name_change, inplace=True)

print("Team names updated")

Team names updated

In [16]:
matches['venue'].unique()

<StringArray>
[                                                'M Chinnaswamy Stadium',
                            'Punjab Cricket Association Stadium, Mohali',
                                                      'Feroz Shah Kotla',
                                                      'Wankhede Stadium',
                                                          'Eden Gardens',
                                                'Sawai Mansingh Stadium',
                             'Rajiv Gandhi International Stadium, Uppal',
                                       'MA Chidambaram Stadium, Chepauk',
                                            'Dr DY Patil Sports Academy',
                                                              'Newlands',
                                                      'St George's Park',
                                                             'Kingsmead',
                                                       'SuperSport Park',
                                                          'Buffalo Park',
                                                 'New Wanderers Stadium',
                                                 'De Beers Diamond Oval',
                                                       'OUTsurance Oval',
                                                     'Brabourne Stadium',
                                          'Sardar Patel Stadium, Motera',
                                                      'Barabati Stadium',
                                             'Brabourne Stadium, Mumbai',
                          'Vidarbha Cricket Association Stadium, Jamtha',
                          'Himachal Pradesh Cricket Association Stadium',
                                                         'Nehru Stadium',
                                                'Holkar Cricket Stadium',
                   'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
                                            'Subrata Roy Sahara Stadium',
                               'Maharashtra Cricket Association Stadium',
                      'Shaheed Veer Narayan Singh International Stadium',
                                    'JSCA International Stadium Complex',
                                                  'Sheikh Zayed Stadium',
                                               'Sharjah Cricket Stadium',
                                   'Dubai International Cricket Stadium',
                  'Punjab Cricket Association IS Bindra Stadium, Mohali',
                                'Saurashtra Cricket Association Stadium',
                                                            'Green Park',
                                                 'M.Chinnaswamy Stadium',
                          'Punjab Cricket Association IS Bindra Stadium',
                                    'Rajiv Gandhi International Stadium',
                                                'MA Chidambaram Stadium',
                                                  'Arun Jaitley Stadium',
                              'MA Chidambaram Stadium, Chepauk, Chennai',
                                              'Wankhede Stadium, Mumbai',
                                      'Narendra Modi Stadium, Ahmedabad',
                                           'Arun Jaitley Stadium, Delhi',
                                      'Zayed Cricket Stadium, Abu Dhabi',
                                    'Dr DY Patil Sports Academy, Mumbai',
                         'Maharashtra Cricket Association Stadium, Pune',
                                                 'Eden Gardens, Kolkata',
      'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh',
 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow',
                  'Rajiv Gandhi International Stadium, Uppal, Hyderabad',
                                      'M Chinnaswamy Stadium, Bengaluru',
                                   'Barsapara Cricket Stadium, Guwahati',
                                        'Sawai Mansingh Stadium, Jaipur',
              'Himachal Pradesh Cricket Association Stadium, Dharamsala',
    'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur',
    'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam']
Length: 58, dtype: str

In [17]:
venue_map = {
    # Chinnaswamy
    'M Chinnaswamy Stadium': 'M Chinnaswamy Stadium',
    'M.Chinnaswamy Stadium': 'M Chinnaswamy Stadium',
    'M Chinnaswamy Stadium, Bengaluru': 'M Chinnaswamy Stadium',

    # Wankhede
    'Wankhede Stadium': 'Wankhede Stadium',
    'Wankhede Stadium, Mumbai': 'Wankhede Stadium',

    # Brabourne
    'Brabourne Stadium': 'Brabourne Stadium',
    'Brabourne Stadium, Mumbai': 'Brabourne Stadium',

    # Eden Gardens
    'Eden Gardens': 'Eden Gardens',
    'Eden Gardens, Kolkata': 'Eden Gardens',

    # Chepauk
    'MA Chidambaram Stadium': 'MA Chidambaram Stadium',
    'MA Chidambaram Stadium, Chepauk': 'MA Chidambaram Stadium',
    'MA Chidambaram Stadium, Chepauk, Chennai': 'MA Chidambaram Stadium',

    # Punjab / Mohali
    'Punjab Cricket Association Stadium, Mohali': 'Punjab Cricket Association Stadium, Mohali',
    'Punjab Cricket Association IS Bindra Stadium': 'Punjab Cricket Association Stadium, Mohali',
    'Punjab Cricket Association IS Bindra Stadium, Mohali': 'Punjab Cricket Association Stadium, Mohali',
    'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh': 'Punjab Cricket Association Stadium, Mohali',

    # Arun Jaitley
    'Feroz Shah Kotla': 'Arun Jaitley Stadium',
    'Arun Jaitley Stadium': 'Arun Jaitley Stadium',
    'Arun Jaitley Stadium, Delhi': 'Arun Jaitley Stadium',

    # Rajiv Gandhi
    'Rajiv Gandhi International Stadium': 'Rajiv Gandhi International Stadium',
    'Rajiv Gandhi International Stadium, Uppal': 'Rajiv Gandhi International Stadium',
    'Rajiv Gandhi International Stadium, Uppal, Hyderabad': 'Rajiv Gandhi International Stadium',

    # DY Patil
    'Dr DY Patil Sports Academy': 'Dr DY Patil Sports Academy',
    'Dr DY Patil Sports Academy, Mumbai': 'Dr DY Patil Sports Academy'
}

matches['venue'] = matches['venue'].str.strip()

matches['venue'] = matches['venue'].replace(venue_map)

Saving the data into the Processed Folder

In [18]:
matches.to_csv("../Data/Processed/matches_clean.csv", index=False)

In [19]:
deliveries.to_csv( "../Data/Processed/deliveries_clean.csv",index=False
)